Fixed trouble in training with multi-gpu
After this error:
AttributeError: 'ParallelModel' object has no attribute '_base_model_initialized'
raise RuntimeError(
RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.

I made this change.